### ISSUE TITLE
No SSL

### ISSUE THREAD

**Issue by damienwebdev** [kristenbaldwin/kristenbaldwin.github.io#1]
Github pages now enables SSL encrypted custom domains by default, yet I don't see it on your domain.

**Comment by kristenbaldwin** [comment]
Thanks @damienwebdev! Looks like I just need to update the IP address my A record points to?
https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

I checked my DNS settings where I got my domain and it is not any of the 4 provided in that link.

**Comment by kristenbaldwin** [comment]
@damienwebdev got it switched over 👍
